// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv6zeeQSySY0mHIcMe7UTntouZhohLHqA',
    appId: '1:822365278847:web:36fc38f5c35eabb5eee54a',
    messagingSenderId: '822365278847',
    projectId: 'coretrack-3b51c',
    authDomain: 'coretrack-3b51c.firebaseapp.com',
    storageBucket: 'coretrack-3b51c.firebasestorage.app',
    measurementId: 'G-N9DHNQY7ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVImo6yQ7ekcNa09ZcRXr3-lIIdEZecig',
    appId: '1:822365278847:android:2d8e577c7be607e6eee54a',
    messagingSenderId: '822365278847',
    projectId: 'coretrack-3b51c',
    storageBucket: 'coretrack-3b51c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLR9kzlufqBL8xLq7pL1dcCfl4XLo596Q',
    appId: '1:822365278847:ios:1605e8c399d738cbeee54a',
    messagingSenderId: '822365278847',
    projectId: 'coretrack-3b51c',
    storageBucket: 'coretrack-3b51c.firebasestorage.app',
    iosBundleId: 'com.example.coreTrackTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLR9kzlufqBL8xLq7pL1dcCfl4XLo596Q',
    appId: '1:822365278847:ios:1605e8c399d738cbeee54a',
    messagingSenderId: '822365278847',
    projectId: 'coretrack-3b51c',
    storageBucket: 'coretrack-3b51c.firebasestorage.app',
    iosBundleId: 'com.example.coreTrackTwo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv6zeeQSySY0mHIcMe7UTntouZhohLHqA',
    appId: '1:822365278847:web:f26b4cb890e933eceee54a',
    messagingSenderId: '822365278847',
    projectId: 'coretrack-3b51c',
    authDomain: 'coretrack-3b51c.firebaseapp.com',
    storageBucket: 'coretrack-3b51c.firebasestorage.app',
    measurementId: 'G-TB3QS12572',
  );
}
